### ISSUE TITLE
[Suggestions Needed] Additional CSS Selectors for extracting embed properties

### ISSUE THREAD

**Issue by novacrazy** [Lantern-chat/embed-service#6]
Custom sites in the config file now support extracting some embed properties from CSS selectors, such as this for extracting the alt-text on XKCD pages:

```toml
[sites.xkcd]
color = 0x96A8C8
domains = ["xkcd.com"]

[sites.xkcd.fields]
image_alt = "div#comic > img < title"
```

where the `< title` syntax specifies to extract from the `title` attribute on the `img` node. 

Full list of available selector fields is [Here](<https://github.com/Lantern-chat/embed-service/blob/3259eb30cb007f4d7a76dd5dee0eb96dad41260c/embed-server/src/config/selectors.rs#L43-L72>).

Suggestions for more sites with consistent html structure are encouraged! Note that these fields take the lowest precedence, so any OEmbed or meta tags will not (currently) be overridden.
